### ISSUE TITLE
.NET Core February 2020 Update - 2.1.16, 3.0.3 and 3.1.2

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#4280]
[3.1.2 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.2/3.1.2.md)
[3.1.2 Download](https://www.microsoft.com/net/download/dotnet-core/3.1)

[3.0.3 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0.3/3.0.3.md)
[3.0.3 Download](https://www.microsoft.com/net/download/dotnet-core/3.0)

[2.1.16 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.16/2.1.16.md)
[2.1.16 Download](https://www.microsoft.com/net/download/dotnet-core/2.1)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/net-core-february-2020/)

Please report any issues you find with 2.1.16, 3.0.3 or 3.1.2, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues

-----
We are experiencing delays in pushing Linux feeds. Here is the list of repositories we are trying to push and as the release is progressing, we will tick them off as each is resolved. 

| Distro | 3.1 | 3.0 | 2.1 |
|--|--|--|--|
| Ubuntu 16.04  | X | X | X |
| Ubuntu 18.04  | X | X | X |
| Ubuntu 19.10  | X | X | X |
| Centos 7      | X | X | X |
| Debian 9      | X | X | X |
| Debian 10     | X | X | X |
| Fedora 30     | X | X | X |
| Fedora 31     | X | X | X |
| OpenSUSE 15   | X | X | X |
| SLES 12       | X | X | X |
| SLES15        | X  | X  | X |
| RHEL 7 / Oracle Linux 7       | X | X | X |

-----
Here is a list of issues that we are tracking and working to resolve with the Feb 2020 release. We'll tick them off as each is resolved. See any linked issue for progress or resolution details.

- [x] Missing Microsoft.EntityFrameworkCore.Relational 3.1.2 on nuget.org
- [ ] The type or namespace name 'Pipelines' does not exist in the namespace 'System.IO' (https://github.com/dotnet/aspnetcore/issues/19133) - [more info](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-312)
- [x] dotnet/announcements (https://github.com/dotnet/announcements/issues/151), the link to the Release Notes of .NET Core 3.1.2 doesn't work.
- [x] No binaries published for macOS/x64 for the new 3.1.102 SDK (missing sdk osx.tar.gz from releases.json)(https://github.com/dotnet/core/pull/4289#event-3052723721)
- [ ] [SqlClient issue](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-312) on ASP.NET Core app update from 3.1.1 to 3.1.2
- [ ] Flakiness in CentOS 7 Linux package repository, encountered >5 times per day (https://github.com/dotnet/core/issues/4298)

**Comment by robarthur** [comment]
Hi, we're having issues installing 2.1.16 on Ubuntu 16.04.  Are the some dependency issues here?

```
ubuntu@ip-172-31-52-133:~$ sudo apt-get update && sudo apt-get install -y dotnet-sdk-2.1
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease                                              
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                                                         
Ign:4 http://us-east-1.ec2.archive.ubuntu.com/ubuntu precise InRelease                                                                                                                
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]                                                                           
Ign:6 http://archive.ubuntu.com/ubuntu trusty InRelease                                                                                              
Hit:7 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease                                                                              
Hit:8 http://download.mono-project.com/repo/debian wheezy InRelease                                                                                  
Hit:9 http://download.mono-project.com/repo/debian wheezy-apache24-compat InRelease                                                                  
Hit:10 https://deb.nodesource.com/node_8.x xenial InRelease                                                                                          
Hit:11 http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2019.2 xenial InRelease                                                                      
Hit:12 http://us-east-1.ec2.archive.ubuntu.com/ubuntu precise Release                                                                                
Hit:13 http://archive.ubuntu.com/ubuntu trusty Release                                                   
Hit:15 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease              
Fetched 216 kB in 0s (259 kB/s)
Reading package lists... Done
W: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/dists/precise/Release.gpg: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.16) but it is not going to be installed
                  Depends: aspnetcore-runtime-2.1 (>= 2.1.16) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by jcb9000** [comment]
Seeing the exact same situation on Ubuntu 19.10:

```
ator@ubuntu:~$ sudo apt-get install dotnet-sdk-3.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-3.1 : Depends: aspnetcore-runtime-3.1 (>= 3.1.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by leecow** [comment]
Hey folks, Keep an eye on the Linux repo checklist at the top of this issue. The upload service is really slow today and we're babysitting everything through.

**Comment by GerardSmit** [comment]
@TaraOverfield in repository [dotnet/announcements](https://github.com/dotnet/announcements/issues) (issue 151, February 2020 .NET Updates), the link to the Release Notes of .NET Core 3.1.2 doesn't work. It currently links to a file in tag 3.1.1, where it should be 3.1.2.

The correct link is: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.2/3.1.2.md

**Comment by jamshedd** [comment]
> @TaraOverfield in repository [dotnet/announcements](https://github.com/dotnet/announcements/issues) (issue 151, February 2020 .NET Updates), the link to the Release Notes of .NET Core 3.1.2 doesn't work. It currently links to a file in tag 3.1.1, where it should be 3.1.2.
> 
> The correct link is: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.2/3.1.2.md

@rbhanda needs to take a look

**Comment by johnkors** [comment]
Going from 3.1.1 to 3.1.2, our app failed to start:

```
Could not load file or assembly 'System.Data.SqlClient, Version=4.6.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

Event log
```
crit: Microsoft.AspNetCore.Hosting.WebHost[6]
      Application startup exception
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.6.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Data.SqlClient, Version=4.6.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

**Comment by yoshiya8** [comment]
Ok so I am running into this over five times a day, each time it seems to work if I try again in a few minutes. It's turning out to be a major productivity problem when we have multiple image builds per day on cluster - each one has to be manually checked and rerun when they fail. I am just wondering if the RPM repo will ever be reliable:
```
Downloading packages:
https://packages.microsoft.com/centos/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata
Trying other mirror.

Error downloading packages:
  netstandard-targeting-pack-2.1-2.1.0-1.x86_64: [Errno 256] No more mirrors to try.
```

**Comment by dagood** [comment]
@yoshiya8 check out https://github.com/dotnet/core/issues/4167 for general status on our effort to get the owners of the service to improve its reliability (and updates when we have them).

That said... we haven't heard of *flakiness* the way you're experiencing it... the typical scenario is a period of downtime (up to 2 hours is "normal") but then back up for everyone. I've opened https://github.com/dotnet/core/issues/4298 based on your comment to discuss more since it doesn't sound related to this release.

**Comment by edgefundefa** [comment]
When migrating from .NET Core 2.2 to 3.1, CORS does not appear to be working properly. I now receive an error saying 

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/users/login. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

In the ConfigureServices method, I have:

`services.AddCors();`

In the Configure method, I have:

```
app.UseRouting();

app.UseCors(options => options
        .AllowAnyOrigin()
        .AllowAnyHeader()
    );

app.UseAuthentication();

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});
```

Note: The documentation on Microsoft's website is using outdated code, such as; UseMvc and IHostingEnvironment.

[https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1](url)

**Comment by ajayjoji01** [comment]
hi,

could you please provide upgrade steps from .net core 2.1 to 2.1.16

**Comment by danielithomas** [comment]
> Seeing the exact same situation on Ubuntu 19.10:
> 
> ```
> ator@ubuntu:~$ sudo apt-get install dotnet-sdk-3.1
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  dotnet-sdk-3.1 : Depends: aspnetcore-runtime-3.1 (>= 3.1.1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> ```

Experiencing the same issue

**Comment by pavinan** [comment]
Is 3.1.2 is deployed to azure. I don't see it in selection.

![image](https://user-images.githubusercontent.com/8724933/77033231-ad4d7180-69cc-11ea-8cb2-c5cdb581dec6.png)

**Comment by kriwec** [comment]
Hello,
On .NET Core 3.1 page release date of 3.1.2 is changed from February to 16 March 2020.
https://dotnet.microsoft.com/download/dotnet-core/3.1
This was done by mistake? Or maybe there is new invisible release?
Size of runtimes and hosting packges still the same as in February.

**Comment by dicksonkimeu** [comment]
How can install .NET 3.1.1 on ubuntu and not 3.1.2 ? Becasuse 3.1.2 has breaking changes

**Comment by svick** [comment]
@dicksonkimeu Based on a [couple](https://stackoverflow.com/a/18888235/41071) of [Stack Exchange answers](https://askubuntu.com/a/190964/5308), you can do the following:

1. `sudo apt update` to refresh the list of available versions
2. `apt policy dotnet-runtime-3.1` to see the available package versions.
3. `sudo apt install dotnet-runtime-3.1=3.1.1-1` to install the desired version of the package.
4. `dotnet --info` to verify you installed the right thing.

Replace the `dotnet-runtime` with a different `dotnet-` package depending on what exactly you need.

**Comment by michalbilinski** [comment]
> Seeing the exact same situation on Ubuntu 19.10:
> 
> ```
> ator@ubuntu:~$ sudo apt-get install dotnet-sdk-3.1
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  dotnet-sdk-3.1 : Depends: aspnetcore-runtime-3.1 (>= 3.1.1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> ```

I experience exactly the same issuet on Ubuntu 20.04. Does anyone know a fix for this?

**Comment by svick** [comment]
@michalbilinski See https://github.com/dotnet/core/issues/4360. Ubuntu 20.04 is currently not supported, packages for it should be available on 12 May. In the meantime, you can try the workarounds mentioned in that issue.

**Comment by michalbilinski** [comment]
> @michalbilinski See #4360. Ubuntu 20.04 is currently not supported, packages for it should be available on 12 May. In the meantime, you can try the workarounds mentioned in that issue.

You are right, thanks!
