### ISSUE TITLE
.NET Core August 2020 Update - 2.1.21 and 3.1.7

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#5057]
[3.1.7 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.7/3.1.7.md)
[3.1.7 Download](https://www.microsoft.com/net/download/dotnet-core/3.1)

[2.1.21 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.21/2.1.21.md)
[2.1.21 Download](https://www.microsoft.com/net/download/dotnet-core/2.1)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/net-core-august-2020/)

Please report any issues you find with 2.1.21 or 3.1.7, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues

-----
Status of availability of SDK on Linux feeds: 

| Distro | 3.1.401 | 3.1.7| 2.1.21 
|--|--|--|--|
| Ubuntu 16.04 |  ✅  |  ✅ | ✅  |
| Ubuntu 18.04 |  ✅ | ✅ |✅ |
| Ubuntu 20.04 |  ✅ |  ✅ | ✅ |
| Centos 7    |  ✅  | ✅| ✅ |
| Debian 9   |  ✅   |  ✅| ✅ |
| Debian 10  |  ✅  | ✅ |✅ |
| Fedora 30  |  ✅   | ✅ |✅ |
| Fedora 31  |  ✅   | ✅ |✅ |
| Fedora 32  |  ✅   | ✅ |✅  |
| OpenSUSE 15 |  ✅  | ✅ | ✅ |
| SLES 12    |  ✅    | ✅  | ✅ |
| SLES15    |  ✅    | ✅  | ✅ |
-----
### Known Issues
If there are any issues with the August 2020 release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

- [ ]  [Snap installer for 3.1.401 SDK failure](https://github.com/dotnet/runtime/issues/40739)  - This was resolved by rebuilding and republishing snap installer for 3.1.401.
- [x] https://github.com/dotnet/core/issues/4822#issuecomment-672959549  releases-index.json was not updated on [storage](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json) - This was resolved by replacing file on blog storage with GitHub file.
- [x] https://github.com/dotnet/core/issues/5057#issuecomment-672251284 Release notes for 3.1.7.md contained wrong VS version for .NET Core SDK 3.1.401 - Release notes were updated to reflect .NET Core 3.1.401 support for Visual Studio 16.7
- [x] Leading and trailing whitespace in releases.json files for CVE name field - This was corrected by removing the white spaces

**Comment by smokedlinq** [comment]
The release notes for 3.1.7 state that it supports Visual Studio 2019 version 16.6, however when running a build on a system with NuGet 5.6.0, Visual Studio 2019 16.6 and .NET core SDK 3.1.401 during the restore we receive the following error:

`Version 3.1.401 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.6.0.22303. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.`

I believe Visual Studio 16.6 comes with MSBuild 16.6 and the just releases Visual Studio 16.7 comes with MSBuild 16.7.

**Comment by mgroetan** [comment]
Today, our Azure Devops hosted build agent builds started failing, after getting its "UseDotNet" task auto-updated from .NET Core 3.1.6's 3.1.302 SDK version to the shiny new .NET Core 3.1.7's 3.1.401 SDK version.

The reason for the problems is our need to install multiple .NET Core SDKs (as mentioned [here](https://stackoverflow.com/questions/57429066/how-to-install-several-net-core-sdk-versions-on-azure-devops)).

For reasons beyond the scope of this issue, we're still having a need for using the .NET Core 2.2.x SDK, in addition to the .NET Core 3.1.x SDK.

We now experienced the following problems when running "NuGet restore" (5.3.1):
1) For a (.NET Framework 4.7.2) project using the "Microsoft.NET.Sdk.WindowsDesktop" project SDK: "_C:\hostedtoolcache\windows\dotnet\sdk\2.2.103\Sdks\Microsoft.NET.Sdk.WindowsDesktop\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json._"
As this particular project SDK type seems to have been introduced in .NET Core 3.0, we were able to work around that by changing the project SDK to only "Microsoft.NET.Sdk".
2) For any .NET Core 3.x project:
"_The nuget command failed with exit code(1) and error(C:\hostedtoolcache\windows\dotnet\sdk\2.2.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1._"

The latter problem could be fixed by specifically requesting the use of .NET Core SDK version 3.1.302.

I have read the release notes, but can't find anything that suggests that this parallel SDK behaviour should have changed.

In the longer term, we will OF COURSE get rid of the old .NET Core 2.2 requirement, but in the short term this prevents us from using any newer SDK version. So, all in all, not a dramatic end result, and probably not a too common scenario, but nonetheless VERY surprising.

**Comment by huwmanatee** [comment]
On Ubuntu 20.04 `dotnet pack` now returns: /usr/share/dotnet/sdk/3.1.401/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error MSB4181: The "PackTask" task returned false but did not log an error.

**Comment by ashkanRmk** [comment]
> After I upgrade my dotnet runtime to 3.1.7
> I got a lot of errors like this in my all projects in vs-code:
> 
> > The type 'IDictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
> 
> these are my info:
> `▶ dotnet --list-runtimes
> 
> Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> `
> 
> `▶ dotnet --list-sdks
> 
> 2.2.402 [/usr/share/dotnet/sdk]
> 3.1.401 [/usr/share/dotnet/sdk]
> `
> 
> `▶ dotnet --version
> 
> 3.1.401
> `
> 
> those projects can run normally. but have a lot of error in dev!
> my os: linux KDE NEON 20.04


My problem was solved by installing latest version of OmniSharp manually.
because of this update break functionality of extension in vs-code.

https://github.com/OmniSharp/omnisharp-vscode/issues/3951

**Comment by soerendalbydk** [comment]
I have a fatal problem using 3.1.7.

I have a EF Core setup in a Class Library (DLL). When I run 

    dotnet ef migrations add Init --context TransferDbContext --verbose

I get the error:

	It was not possible to find any compatible framework version
	The framework 'Microsoft.NETCore.App', version '3.1' was not found.
	  - The following frameworks were found:
		  3.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

	You can resolve the problem by installing the specified framework and/or SDK.

	The specified framework can be found at:
	  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1&arch=x64&rid=win10-x64	  

The call failing is:

	dotnet exec 
		--depsfile C:\tfs\DigitalEksamenIntegration\DigitalEksamenIntegrationBusiness\bin\Debug\netcoreapp3.1\win-x64\DigitalEksamenIntegrationBusiness.deps.json 
		--additionalprobingpath C:\Users\dalby\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" 
		--runtimeconfig C:\tfs\DigitalEksamenIntegration\DigitalEksamenIntegrationBusiness\bin\Debug\netcoreapp3.1\win-x64\DigitalEksamenIntegrationBusiness.runtimeconfig.json 
		C:\Users\dalby\.dotnet\tools\.store\dotnet-ef\3.1.0\dotnet-ef\3.1.0\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations 
		add Init --context TransferDbContext 
		--assembly C:\tfs\DigitalEksamenIntegration\DigitalEksamenIntegrationBusiness\bin\Debug\netcoreapp3.1\win-x64\DigitalEksamenIntegrationBusiness.dll 
		--startup-assembly C:\tfs\DigitalEksamenIntegration\DigitalEksamenIntegrationBusiness\bin\Debug\netcoreapp3.1\win-x64\DigitalEksamenIntegrationBusiness.dll 
		--project-dir C:\tfs\DigitalEksamenIntegration\DigitalEksamenIntegrationBusiness\ 
		--language C# 
		--working-dir C:\tfs\DigitalEksamenIntegration\DigitalEksamenIntegrationBusiness 
		--verbose 
		--root-namespace DigitalEksamenIntegration.Business

My 

    dotnet --info

Lists following:

	.NET Core SDK (reflecting any global.json):
	 Version:   3.1.401
	 Commit:    5b6f5e5005

	Runtime Environment:
	 OS Name:     Windows
	 OS Version:  10.0.18363
	 OS Platform: Windows
	 RID:         win10-x64
	 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

	Host (useful for support):
	  Version: 3.1.7
	  Commit:  fcfdef8d6b

	.NET Core SDKs installed:
	  3.1.401 [C:\Program Files\dotnet\sdk]

	.NET Core runtimes installed:
	  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

	To install additional .NET Core runtimes or SDKs:
	  https://aka.ms/dotnet-download

and `dotnet-core-uninstall list` lists

	This tool can not uninstall versions of the runtime or SDK that are 
		- SDKs installed using Visual Studio 2019 Update 3 or later.
		- SDKs and runtimes installed via zip/scripts.
		- Runtimes installed with SDKs (these should be removed by removing that SDK).
	The versions that can be uninstalled with this tool are:

	.NET Core SDKs:
	  3.1.401  x64    [Used by Visual Studio. Specify individually or use --force to remove]

	.NET Core Runtimes:

	ASP.NET Core Runtimes:

	.NET Core Runtime & Hosting Bundles:

I have been trying to setup a `global.json` but it did not seem to have an effect.

My `cjsproj` looks like this (reduced version):

			<Project Sdk="Microsoft.NET.Sdk">
			  <PropertyGroup>
				<TargetFramework>netcoreapp3.1</TargetFramework>
				<RootNamespace>DigitalEksamenIntegration.Business</RootNamespace>
				<RuntimeFrameworkVersion>3.1</RuntimeFrameworkVersion>
				<RuntimeIdentifier>win-x64</RuntimeIdentifier>
			  </PropertyGroup>

			  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
				<PlatformTarget>AnyCPU</PlatformTarget>
			  </PropertyGroup>


			  <ItemGroup>
				<Reference Include="EntityFramework">
				  <HintPath>..\DigitalEksamenIntegration.Web\Lib\EntityFramework.dll</HintPath>
				</Reference>
			  </ItemGroup>
			  <ItemGroup>
				<Folder Include="Migrations\" />
			  </ItemGroup>
			  <ItemGroup>
				<WCFMetadata Include="Connected Services" />
			  </ItemGroup>
			  <ItemGroup>
				<None Update="MailReport_Layout.template.txt">
				  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
				  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
				</None>
				<None Update="MailReport_StudentsMissingInRegistrations.template.txt">
				  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
				  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
				</None>
			  </ItemGroup>

			</Project>

Some reports suggested that this was a tooling problem so I tried:

       dotnet tool uninstall -g dotnet-ef
       dotnet tool install -g dotnet-ef --version 3.1.7

But that did not work either. I have tried to remove all Core SDK's and all Core Runtime and reinstall this latest version. Should I try to reinstall Visual Studio?

Any help is appreciated.

Thanks in advance.

Kind regards
Soeren

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/5170
