### ISSUE TITLE
Theme: Enterprise and LTS

### ISSUE THREAD

**Issue by jamshedd** [dotnet/core#5238]
.NET 6.0 will be a Long-Term Support (LTS) release. We see many enterprises prefer our LTS releases over Current releases for their longer support (relative to Current releases), they pick an LTS version so they don’t have to move forward every year. This is not very different from what we see with OS LTS versions – enterprise customers go from one LTS to the next and skip the in-between SAC releases. Since .NET 6.0 will be the successor to 3.1 LTS we expect customers presently using 3.1 LTS and wanting to target the next LTS will pick 6.0 LTS. We will support 3.1 through December 2022, so once .NET 6.0 ships, customers will have 1 year to plan for, rebuild and test their apps and complete their deployment. Customers that cannot migrate their apps to 6.0 in this timeframe will probably ask us to provide longer support.  

If customers can successfully complete their migration forward in this 1-year period everyone benefits. So, it is in everyone’s interest that we do everything we can to enable customers to come forward to 6.0 as easily, smoothly and quickly as possible. 

Epics under this Theme:

- [x] [Enterprises have a first class experience acquiring and deploying .NET 6.0](https://github.com/dotnet/core/issues/5240).
- [x] [.NET Core is supported in air-gapped environments/private clouds](https://github.com/dotnet/core/issues/5435).
- [x] [Enterprises get first-class support when using .NET 6.0 on Linux](https://github.com/dotnet/core/issues/5333).
- [x] [Linux package support is reliable and complete](https://github.com/dotnet/core/issues/5436)
- [x] [.NET Core can be reliably built from source](https://github.com/dotnet/core/issues/5437)
- [ ] [Path to migrate an app from Framework to .NET 6.0 is well understood and streamlined](https://github.com/dotnet/core/issues/5396)
- [ ] https://github.com/dotnet/runtime/issues/54519

**Comment by weedkiller** [comment]
Build in Drop in options for ASP web MVC & [cloud apps Identity with Tenant](https://github.com/dotnet/aspnetcore/issues/26625#issuecomment-704390630), Users, Groups (Like LDAP), Authentication and UI management.

### Multitenant Groups Management is _not_ trivial and still missing in .NET unlike JAVA JSR native support.  

This complexity of this implementation leaves the apps on .NET framework vulnerable, this reference or template implementation should be provided by Microsoft (so that people can refer security threats to Microsoft) and not to the developer to implement this is, its beyond his scope - this is serious security issues.
