### ISSUE TITLE
Epic: Enterprises have a first class experience acquiring and deploying .NET 6.0

### ISSUE THREAD

**Issue by jamshedd** [dotnet/core#5240]
User Stories under this Epic:

- [ ] [As an enterprise IT admin I have supported tools that help in the detection, deployment and cleanup of .NET Core installs at scale](https://github.com/dotnet/core/issues/5441)
- [x] [As a developer I am able to process release metadata for .NET Core updates easily so I can leverage this in my deployment process](https://github.com/dotnet/core/issues/5440)
- [ ] [As a .NET developer I can refer to the source for the detection and deployment tool so I can use similar patterns myself](https://github.com/dotnet/core/issues/5442)
- [ ] [As a .NET container image user I have a clear accounting of vulnerabilities across the layers of my base-image](https://github.com/dotnet/core/issues/5463)
