### ISSUE TITLE
Epic: Enterprises get first-class support when using .NET 6.0 on Linux

### ISSUE THREAD

**Issue by jamshedd** [dotnet/core#5333]
User Stories under this Epic:

- [ ] [Support engineers have complete and up to date playbooks so they can deliver effective .NET diagnostic support to users on Linux](https://github.com/dotnet/core/issues/5452)
- [ ] [Support engineers have a good understanding of the diagnostics tools available so they can deliver effective diagnostic support to users on Linux](https://github.com/dotnet/core/issues/5453)
- [ ] [Support engineers have sufficient hands on time/experience with Linux to effectively support customers using Linux](https://github.com/dotnet/core/issues/5454)
- [ ] [Support engineers have a solid understanding of .NET Core Linux distro support so they can effectively communicate that to customers](https://github.com/dotnet/core/issues/5456)
- [ ] [Members of the .NET Core team have resources to review experiences for Linux developers so they can deliver the right experiences](https://github.com/dotnet/core/issues/5455)
