### ISSUE TITLE
.NET Core October 2020 Update - 2.1.23 and 3.1.9

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#5347]
[3.1.9 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.9/3.1.9.md)
[3.1.9 Download](https://www.microsoft.com/net/download/dotnet-core/3.1)

[2.1.23 Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.23/2.1.23.md)
[2.1.23 Download](https://www.microsoft.com/net/download/dotnet-core/2.1)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/net-core-october-2020/)

Please report any issues you find with 2.1.23 or 3.1.9, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues

-----
Status of availability of SDK on Linux feeds: 

| Distro | 3.1.9| 2.1.23 
|--|--|--|
| Ubuntu 16.04   | ✅  | ✅ |
| Ubuntu 18.04| ✅  | ✅ |
| Ubuntu 20.04 | ✅  | ✅ |
| Ubuntu 20.10 |   | |
| Centos 7   | ✅  | ✅ |
| Debian 9    | ✅  | ✅ |
| Debian 10   | ✅  | ✅ |
| Fedora 30 | ✅  | ✅ |
| Fedora 31 | ✅  | ✅ |
| Fedora 32   | ✅  | ✅ |
| Fedora 33  | ✅  | ✅ |
| OpenSUSE 15 | ✅  | ✅ |
| SLES 12     | ✅ | ✅ |
| SLES15   | ✅  | ✅ |
-----
### Known Issues
If there are any issues with the October 2020 release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

- [x]  We are experiencing delays in Linux feed uploads for 2.1. We will update the list as the upload finishes and validated

- [x]  Unable to install .NET Core 3.1 on OpenSUSE 15. https://github.com/dotnet/core/issues/5350

- [x]  Unable to install .NET Core 2.1 on RHEL 7.

- [ ] Unable to install .NET Core 2.1 & .NET Core 3.1 on Ubuntu 20.10.https://github.com/dotnet/core/issues/5017#issuecomment-708508472

- [x] Unable to install .NET Core 2.1/3.1 on Ubuntu 18.04 and 20.04 https://github.com/dotnet/core/issues/5373 https://github.com/dotnet/core/issues/5372

**Comment by jvymazal** [comment]
Hello, it is more likely problem on my machine however maybe you can extract some corner-case issue from it, currently dotnet 3.1.9 is dumping core on its own: #5534

**Comment by rbhanda** [comment]
Closing in favor of https://github.com/dotnet/core/issues/5546

**Comment by dvolochx** [comment]
Hello. I'm trying to build a project for Net Core 3.1.9 on Linux, but I get the following message:

The current .NET SDK does not support targeting .NET Core 3.1.9.

Can you tell me what I have to install?
