### ISSUE TITLE
Epic: Deliver on the remaining .NET Core customer promises from .NET 5

### ISSUE THREAD

**Issue by cathysull** [dotnet/core#5395]
_This is a draft/proposed Epic and not committed for .NET 6.0 yet._

# Why
In .NET 5, many factors contributed to the fact that some features were developed in one area, and were not always supported across the entire stack or for all workloads. While many of these features are dialable, investing in finishing these promises will both help .NET developers to better adopt these platform features as we continue to evolve the .NET platform. 

# Summary
Finishing the remaining promises from .NET 5 includes features that support cross-cutting platform enablement and ensure that we have a more complete end-to-end experience in the .NET platform. Many of these features will require more definition and scoping during .NET 6 planning beyond what is described in the User Stories below.

# User Stories

- [ ] Developers can build libraries for HTTP3 to meet their client/server needs https://github.com/dotnet/runtime/issues/43546 (P0)
- [ ] Developers can confidently generate single file apps that work for the supported target platforms https://github.com/dotnet/runtime/issues/43540 (P0)
- [ ] Add Streaming API support to MVC https://github.com/dotnet/aspnetcore/issues/11558 (P1)
- [ ] .NET Core developers can verify more APIs for their correct usage to speed up their development https://github.com/dotnet/runtime/issues/43617 (P1)
- [ ] Developers using C# nullable reference types can use them with more Microsoft SDKs to validate correctness of their code https://github.com/dotnet/runtime/issues/43619 (P1)
- [ ] Expanding Linker tooling in VS (P1)
- [ ] Improvements to web api experience around OpenAPI and API Explorer https://github.com/dotnet/aspnetcore/issues/27889
- [ ] Developers should be guided away from more obsolete APIs in .NET 6 https://github.com/dotnet/runtime/issues/46767
- [ ] ASP.NET Core and SPAs in .NET 6 https://github.com/dotnet/aspnetcore/issues/27887
- [ ] Evaluate what we want to do with Bootstrap for .NET 6 https://github.com/dotnet/aspnetcore/issues/23017
- [ ] Narrow the feature gap between EF Core and EF6 https://github.com/dotnet/efcore/issues/24106

**Comment by ericsampson** [comment]
One that I'd really love to see included is this C#10 proposal:
https://github.com/dotnet/csharplang/issues/3630

If this isn't the right place to include it under, please LMK! Thanks : )

**Comment by cathysull** [comment]
Closing from .NET 5
