### ISSUE TITLE
Theme: Grow the .NET ecosystem through increased Quality, Confidence, and Support

### ISSUE THREAD

**Issue by terrajobst** [dotnet/core#5415]
### Summary

There is a [.NET Foundation sponsored working group](https://github.com/dotnet-foundation/ecosystem-growth) that tries to figure out what should be done here. The problem statement from our perspective [is here](https://github.com/microsoft/dotnet/blob/master/docs/ecosystem-issues.md).

### Epics

Epics under this Theme:

- [ ] [Developers have access to guidance & tools that supports them in building cross-platform packages](https://github.com/dotnet/core/issues/5529)
- [ ] [We have a solid understanding of how well the .NET ecosystem serves our users](https://github.com/dotnet/core/issues/5727)
- [ ] [Grow the .NET ecosystem](https://github.com/dotnet/core/issues/5731)

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
