### ISSUE TITLE
Theme: .NET has a great client app development experience

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/core#5423]
### Summary

With .NET 6, we want to bring mobile developers forward to a unified .NET development experience and enable developers investing today in web and client development experiences to bring those investments to the desktop. In .NET 6, we will be integrating Xamarin into the .NET SDK, bringing support for the latest project system, BCL, and Target Framework Monikers to align with the rest of the .NET ecosystem. We want to expand Blazor to allow Blazor applications to run as native desktop applications, boost mobile application performance, improve inner-dev loop experiences, and maintain app size with Xamarin.

### Epics

Note: These experiences are proposed for .NET 6 and not yet committed.
Epics under this Theme:

- [ ] [Epic: Xamarin developers can upgrade to and use the latest .NET SDKs in their existing applications](https://github.com/dotnet/xamarin/issues/2) | dotnet/xamarin#2
- [ ] [Epic: Xamarin developers have improved app performance and share more code with .NET 6](https://github.com/dotnet/xamarin/issues/21) | dotnet/xamarin#21
- [ ] [Epic: Blazor developers can target and deploy their applications to desktop platforms, allowing them to run natively](https://github.com/dotnet/aspnetcore/issues/27217) | dotnet/aspnetcore#27217
- [ ] [Epic: Desktop developers can package, distribute, release, and update their applications to multiple desktop platforms and architectures](https://github.com/dotnet/core/issues/5462)
- [ ] [WinForms developers have great experience with their .NET Core and .NET 5, 6 ,... apps](https://github.com/dotnet/core/issues/5907)

**Comment by josepvg** [comment]
Ok, now we will be able to compile Blazor to native apps?!?. I must admit I'm getting a bit lost in this multiplatform development world. I'm currently using Xamarin for my mobile development. But now if I understand this correctly we have 3 options:
1. Xamarin (android/ios/uwp).
2. Platform UNO ( android/ios/uwp/wasm/windows/macos)
3. Blazor (wasm.... android/ios/uwp)

I get the feeling that all three are tackling the same problem.
Which one is the best option?, Which is most likely to be supported for the longest time? I really don't want to invest in learning all three.

**Comment by moflaherty** [comment]
Would love to see Fluent UI ported to Blazor for a rich set of controls and styling. That would amp up the native developer experience.

**Comment by Luiz-Monad** [comment]
Know what would be cool, if XAML worked in all platforms, including webbrowsers.

**Comment by sinand99** [comment]
Microsoft should calm down on this cross-platfrom craziness. I don't want stupid bloated web controls on my desktop. Those belong to the browser only.

**Comment by petemidg32** [comment]
@Luiz-Monad Have you not heard of Ooui ? That is a .net core library that lets you add (say) a .net core mvc project into a mobile app alongside the ios and android projects, and then just run the app targeting this project into a browser.
I have tried doing this using instructions available online and found it not a smooth process: I had to remove the button style I was using (via a static resource) and then remove the button property 'TextTransform'. That's what I've discovered so far!

**Comment by dotMorten** [comment]
My main issue with client app dev support, is that we've lost the ability to have a webrequest cache in .NET Core that we had "built in" in .NET Framework. This can significantly slow down repeated web-requests in a client app that will often check back on URLs for for instance status updates or fresh data, but not taking advantage of cache-control and etag headers, causing increased network data-load.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
