### ISSUE TITLE
.NET apps work well in constrained environments

### ISSUE THREAD

**Issue by glennc** [dotnet/core#5434]
Customers deploying to Kubernetes are generally going to want to apply memory and CPU constraints to their apps. This provides safety mechanisms for apps with memory leaks or bugs that cause runaway CPU and also helps ensure a minimum amount of density on a cluster. We want to be able to provide guidance on what those memory limits should be as well as reduce our memory consumption if possible. Perhaps providing configuration that can be set to work better with particular sets of constraints.

We intend to look at memory usage for a few of our benchmarks (gRPC and maybe Fortunes to begin with), looking for opportunities to improve. In an ideal world we would reduce our memory consumption compared to Go/Node/Rust and be able to provide detailed instructions to customers setting limits on their .NET processes.

### Work Items
- [ ] Improve .NET application startup and steady-state performance: #5438
- [ ] Reduce runtime image size on disk: #5439
- [x] Enable Environment.ProcessorCount to return total machine processors in containers https://github.com/dotnet/runtime/issues/48094
- [x] Container limits not supported by .NET runtime in process isolation mode -- Windows containers https://github.com/dotnet/runtime/issues/46889
- [ ] gRPC apps in Kubernetes scale correctly using gRPC client-side load balancing #5495
- [ ] gRPC apps can make resilient API calls with client retry support #5493
- [ ] Developers and limit the execution of activities https://github.com/dotnet/core/issues/6196

**Comment by madhub** [comment]
Should also provide guidance on selecting **Workstation** or **Server GC** on constrained environments

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
