### ISSUE TITLE
.NET Core can be reliably built from Source

### ISSUE THREAD

**Issue by jamshedd** [dotnet/core#5437]
User Stories under this Epic:

- [ ] [Arcade powered source build - finish what we started](https://github.com/dotnet/core/issues/5448)
- [ ] [As a developer using Debian (and downstream repos like Ubuntu) I can use a native feed/AppStream to get .NET Core](https://github.com/dotnet/core/issues/5449)
- [ ] [As a developer I can easily build on the desktop, either the whole product or parts of the product from source](https://github.com/dotnet/core/issues/5450)
