### ISSUE TITLE
Epic: Desktop developers can package, distribute, release, and update their applications to multiple desktop platforms and architectures

### ISSUE THREAD

**Issue by rconard** [dotnet/core#5462]
### Summary

.NET 6 is introducing multiple new targets including Xamarin 6 and the possibility for Blazor client applications. As these applications will offer deployment scenarios on platforms and architectures that are not currently supported for client applications, we will expand our deployment tooling to cover these scenarios.

>Note: This is a proposed experience for .NET 6 and not yet committed.

### User Stories

User Stories under this Epic:

- [ ] [Xamarin 6 developers building desktop applications need to package and update their applications for multiple platform targets](https://github.com/dotnet/core/issues/5460).
- [ ] [.NET 6 desktop application developers need to manage their build pipelines, versions, telemetry, and channels for their releases](https://github.com/dotnet/core/issues/5461).
- [ ] [Create installable artifacts for Blazor hybrid desktop apps for Windows, macOS, and Linux](https://github.com/dotnet/aspnetcore/issues/27234).

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
