### ISSUE TITLE
New developers can learn .NET by building, running and debugging Simple Apps

### ISSUE THREAD

**Issue by cartermp** [dotnet/core#5473]
### Summary

Simple Apps are .NET apps with the following properties:

* C# files that are top-level programs / F# scripts
* Modern language features that emphasize less code to accomplish a task are emphasized
* No project file required
* Loadable by all .NET tooling (CLI, VSCode, Visual Studio)
* Output executable is a single binary that is next to the source file in the user's directory

A Simple App is a starting point for developers who are learning .NET. As their app's capabilities grow, they can do things like add a project file to support their development needs.

### User Stories

User Stories under this Epic:

- [ ] ["dotnet new" has a simple and predictable flow for new users](https://github.com/dotnet/core/issues/5480).
- [ ] [New developers can create a Simple .NET App from the command line](https://github.com/dotnet/core/issues/5481)
- [ ] [Modern C# is emphasized for newcomers](https://github.com/dotnet/core/issues/5482)
- [ ] [C# Simple Apps have a natural grow-up path when developers want to expand their app's capabilities](https://github.com/dotnet/core/issues/5483)
- [ ] [The output of a C# Simple App is easy and intuitive to find](https://github.com/dotnet/core/issues/5484)

**Comment by IntegerMan** [comment]
I'd love to see some consideration of error messages as part of this effort. Compiler errors are scary for new developers. Even things that you think should be intuitive like "Not all code paths return a value" are overwhelming for someone just starting out writing methods. Compiler errors are naturally a bit scary and part of how they're presented in Visual Studio pushes that new developer mindset into panic mode, which makes them less able to reason about the error.

I'd love to see some form of wording improvements alongside some actual plain text description of common errors such as casting issues, using a variable that's been defined but not initialized, array index out of bounds, not all code paths returning a value, incorrect return type from a method, etc.

In an ideal world I'd be able to see a small two paragraph beginner friendly explanation in Visual Studio with an image of bad code (code not returning a value, for example) and fixed code to illustrate the type of the error it was. Not something specific to the user's code, just some less terrifying stuff to help new developers be less terrified of what they're encountering and less intimidated by output built for expert users.

**Comment by rgwood** [comment]
I _love_ this proposal and I hope it makes it for .NET 6!

One thing to add: as described, Simple Apps seem like they will also be popular for scripting purposes and ad-hoc coding. The potential audience is much broader than just “developers who are learning .NET.”

I could see myself using a Simple App in CI pipelines, to replace Python/Bash/PowerShell scripts. Similarly, I could see myself using a Simple App for one-off exploratory development (instead of creating yet another console app with a csproj).

**Comment by teo-tsirpanis** [comment]
Related: dotnet/sdk#12328

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
