### ISSUE TITLE
Improve inner-loop performance for .NET developers

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/core#5510]
### Summary
Inner-loop performance is critical to providing the developer experiences that are increasingly expected/demanded by developers. How fast developers can make code changes and see the resulting impact in their apps is directly proportional to how productive they can be.

When using other platforms, many of the common inner-loop operations are faster, sometimes dramatically so, than the equivalent when using .NET. First-time user impressions may be negatively impacted by such differences, to the point that it deters their choice of .NET as a developer platform.

### Epics

Epics under this Theme:

- [x] [Improve performance of CLI/SDK/MSBuild that relate to the developer inner-loop](https://github.com/dotnet/msbuild/issues/5876).
- [ ] [Improve and modernize the launch/debug/update loop](https://github.com/dotnet/core/issues/5511)
- [x] [Hot Reload application changes during development inner-loop from the .NET CLI](https://github.com/dotnet/sdk/issues/15825)
- [x] [Hot Reload for Blazor Components](https://github.com/dotnet/aspnetcore/issues/5456)
- [x] [Hot Reload for ASP.NET Core](https://github.com/dotnet/aspnetcore/issues/18486)
- [x] [Reimplement the Razor compiler using source generators & introduce incrementality](https://github.com/dotnet/aspnetcore/issues/26902)
- [ ] [Blazor WebAssembly Hot Restart](https://github.com/dotnet/aspnetcore/issues/27272)
- [x] [Support Code Hot Reload (EnC) for Razor](https://github.com/dotnet/aspnetcore/issues/27269)
- [ ] [ASP.NET Core Hot Restart](https://github.com/dotnet/aspnetcore/issues/27270)
- [ ] [Xamarin developers have an improved development experience on .NET 6](https://github.com/dotnet/xamarin/issues/3)
- [x] [Ensure the BCL supports Hot Reload](https://github.com/dotnet/runtime/issues/45023)
- [x] [Reduce EF Core application startup time via compiled models](https://github.com/dotnet/efcore/issues/1906)

**Comment by squalsoft** [comment]
This is really very critical. From day to day i have pain with slow builds compared to Go compilation.

**Comment by MatthewLymer** [comment]
I notice this quite a bit when doing TDD, add one line of code, wait 30 seconds for it to compile and validate my test.  I guess this would apply to the first two epics.

**Comment by mkArtakMSFT** [comment]
Updated the link for the `Hot reload for Blazor components` link.

**Comment by srxqds** [comment]
will it add support jit reload on monovm?

**Comment by dneimke** [comment]
Consider replacing the wwwroot/lib artifacts in new projects with libman config

**Comment by SimonCropp** [comment]
is this expected to break IL weavers like postsharp and fody?

**Comment by SimonCropp** [comment]
has a fast loop been considered for test execution? as in patching into a process that can run test?

**Comment by przemo098** [comment]
I think development in C# should give good developer experience as in this talk: https://youtu.be/Yu9zcJJ4Uz0?t=416
In the end users will use languages which provide best development experience and other one will die.
And I think quick updating your code is critical in development like hot reloading of js in React / Angular...
I think in compilation should look like in https://www.snowpack.dev/ for js :)

**Comment by NejcBW** [comment]
@przemo098 I think Vite.js is the new gold standard that all other tools will be compared with in the foreseeable feature.

**Comment by Liero** [comment]
On a related note: 

When running `dotnet watch` in terminal I often
1. cannot see build errors/warning in VS error window
2. cannot run tests, because VS runs it's own build and obj/*.dll files are locked by the `dotnet watch`.

In other words, I either use `dotnet watch` and loose lot of VS tooling support, or I use run the app using VS (Debug or Run without debugging) and loose some of the live reload functionality.

Also, when debugger is attached and app is rebuilt, it could automatically reattach, resp. never detach. Just like when I set breakpoint in javascript file in Chrome's developer tools and refresh a page.

**Comment by daniel-p-tech** [comment]
When can developers expect hot reload of Blazor (WASM) to be available? This is such a huge productivity enhancement that is crucial in successful adoption of Blazor.

**Comment by redcatH** [comment]
super
Reduce EF Core application startup time via compiled models

**Comment by Polymathical** [comment]
Inner loop. smh. The terminology gets more embarrassing each... outer loop.

**Comment by paramjeetSP** [comment]
Great Efforts.

**Comment by wocar** [comment]
THIS IS GREAT. THANK YOU!!!

**Comment by DamianEdwards** [comment]
Closing this out as it pertains to work done in .NET 6.0
