### ISSUE TITLE
Epic: Developers have access to guidance & tools that supports them in building cross-platform packages

### ISSUE THREAD

**Issue by terrajobst** [dotnet/core#5529]
We need to make it easier to multi-target across operating systems and architectures, which also includes better support for RID-based multi-targeting.

### User Stories

- [ ] As a package author, I can use #if to perform version checks dotnet/sdk#14540
- [x] Completion should support preprocessor symbols https://github.com/dotnet/roslyn/issues/49694
- [ ] Package authors can multi-target between runtime identifiers (RID) #5699
- [ ] Package authors can validate that their multi-targeted packages are well-formed #5700
- [ ] Package authors can validate that they didn't accidentally make an API breaking change #5701
- [ ] Package authors have guidance for building multi-targeted packages #5702
- [ ] Package authors have guidance for building packages that deploy native code #5703
- [ ] As a developer, I get compile time diagnostics for unsupported APIs https://github.com/dotnet/runtime/issues/47228
- [ ] As a package consumer, I can replace a package in my graph with a different ID and version https://github.com/dotnet/core/issues/5864

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
