### ISSUE TITLE
Developers can call gRPC services from .NET Framework

### ISSUE THREAD

**Issue by JamesNK** [dotnet/core#5713]
**Problem:**

MS guidance is to migrate WCF apps to gRPC where possible when moving from .NET Framework to .NET Core. Migrating multiple inter-connected apps is a big task and is difficult to do all at once. There is a transitionary period where older .NET Framework apps will hang around and need to use newer gRPC services. There needs to be a good gRPC client solution on .NET Framework.

Our new gRPC client, Grpc.Net.Client, supports .NET Core 3 and later. .NET Framework apps must use Grpc.Core on .NET Framework. Grpc.Core is functional, but its TLS stack is problematic because it doesn't integrate with Windows cert store and breaks guidance. This blocks some customers from calling gRPC from the .NET Framework, and complicates their migration from .NET Framework to .NET Core/.NET 5.

**Solution:**

Grpc.Net.Client could be updated to support .NET Framework by using WinHttpHandler as its HTTP stack. WinHttp doesn't have the TLS issues that Grpc.Core does and would unblock customers.

For Grpc.Net.Client to support .NET Framework, WinHttpHandler will need to be updated to support HTTP/2 trailing headers, and to verify that it supports bidirectional streaming:

- [x] WinHttpHandler HTTP/2 trailing headers - https://github.com/dotnet/runtime/issues/44778
- [x] Add .NET Standard 2.0 support to Grpc.Net.Client - https://github.com/grpc/grpc-dotnet/issues/1176

Future:
- [x] WinHttpHandler - HTTP/2 bidirectional streaming - https://github.com/dotnet/runtime/issues/44784 ... 2021/1/6 status: Not supported by WinHttp yet

**Comment by danmosemsft** [comment]
Making sure this is on @karelz radar.

**Comment by danmosemsft** [comment]
@karelz is discussing and working on costing.

**Comment by karelz** [comment]
@danmosemsft I will remove the Team:Libraries label, as it is now present on the one depencency. This issue should track the end-to-end User Story, which will require changes in gRPC as well (to be added above by @JamesNK I assume).

**Comment by danmosemsft** [comment]
> (to be added above by @JamesNK I assume).

@JamesNK are you planning to add this? We presumably need to establish that either all dependencies are committed, or none.

**Comment by JamesNK** [comment]
Added https://github.com/grpc/grpc-dotnet/issues/1176. Is it ok that it is not in a dotnet repo? I can create an issue in dotnet/aspnetcore if it is.

PR to support .NET standard 2.0 is already mostly done - https://github.com/grpc/grpc-dotnet/pull/1118. I wanted it to verify that WinHttp changes actually work end-to-end. Interop tests show that they do 🍰

**Comment by danmosemsft** [comment]
@JamesNK it's probably a good idea to make a proxy issue in aspnetcore so it shows up in themesof.net.

**Comment by JamesNK** [comment]
The grpc/grpc-dotnet issue shows up on the website.

![image](https://user-images.githubusercontent.com/303201/105107776-aaa43700-5b1d-11eb-9deb-2bc023b88b22.png)

**Comment by danmosemsft** [comment]
what wizardry is this? I guess we query that repo too. Great.

**Comment by shirhatti** [comment]
@karelz @JamesNK Based on our conversation today supporting unary + server streaming calls with WinHttpHandler will happen in 6.0. As such I'm marking this as P1.

**Comment by karelz** [comment]
@shirhatti I am a bit puzzled. You told us the priority is P2. Yes, we plan to do it, but that should be orthogonal to priority. Shouldn't priority be based on scenario importance relative to other scenarios? That way it can be effectively used in future if plans change, more things are discovered, or higher priorities come in ...

**Comment by karelz** [comment]
@shirhatti @JamesNK ping?

**Comment by JamesNK** [comment]
Last I heard it was P2 but I'm not involved in meetings where this gets decided 🤷‍♂️

**Comment by shirhatti** [comment]
Oops. I just accidentally marked this as P1 😢

**Comment by yezilife** [comment]
We would love to see this as P1 if not P0 : )

**Comment by takekazuomi** [comment]
Current Grpc.Net.Client .NET Framework support is limited to Windows 10 Build 19622 or later. This is very strict and we can't use Grpc.Net.Client with App Service and .NET Framework. Will the Build restrictions be removed?

**Comment by JamesNK** [comment]
The short answer is no, a minimum version of Windows will always be required.

The long answer is gRPC requires HTTP/2. .NET Framework doesn't have built-in support for HTTP/2. WinHTTP, a HTTP client build into Windows, provides HTTP/2 for Grpc.Net.Client on .NET Framework. Features needed to be added to WinHTTP and they are only available on newer versions of Windows.

**Comment by takekazuomi** [comment]
It's painful that grpc-dotnet can't be used with App Service. For the time being, I use Grpc.Core for the .NET Framework. I expect the App Service Windows OS to be updated before Grpc.Core is deprecated.

**Comment by Bonuspunkt** [comment]
> a minimum version of Windows will always be required

which version of Windows Server is required?

**Comment by karelz** [comment]
@JamesNK all work items seem to be addressed now. Should we close it as done?

**Comment by JamesNK** [comment]
DONE

**Comment by schh** [comment]
Pardon my ignorance here but i'm actually about to go insane trying to work out what this Windows 10 Build 19622 actually is, when it was released, was it even released, if so when. Any build history information like here:

[https://docs.microsoft.com/en-us/windows/release-health/release-information](url)

have no mention of this build number anywhere, and the only build number that looks like it follows this is at 19044 for the 21H2 version. I'm confused to say the least. 

I would just like to know if implementing  the current Grpc.Net.Client in my .NET framework clients is something i should do or if i'm better of just sticking to Grpc.Core for now. Any clarification on this would be grweatly appreciated.

**Comment by schh** [comment]
Thank you for the swift reply, i guess that mean i'm sticking to Grpc.Core for now.

**Comment by alberto-chiesa** [comment]
First of all, thanks @JamesNK  for raising this point.

I have a major concern, however: .NET Framework is still going to be a requirement in a lot of enterprise environments for a long time (at least, relatively to the pace the .NET versions are moving currently), and OS version requirements should also be taken into account.

AFAICT, the only way we are going to have anything gRPC related working in Win 2016 is going with .Net Framework + Grpc.Core. Am I correct?

If so, this means that Grpc.Core must "stay alive" at least for the lifetime of Win 2016 (which is 2022, or 2027 for the extended lifetime support), and possibly Win Server 2019, if it's true that gRPC is "the way forward".

I think the upgrade path for an enterprise application (think WCF + .Net Framework + Win Server 2016) is at the moment sketchy.

I would like to go to gRPC+.NET 5 in just one step, but that is not going to work: it's too much work in one step.

I would like to upgrade to gRPC while still in .NET Framework, and then get away from WCF with .NET Core 3 or .NET 5.
The planned deprecation of Grpc.Core is a frozen shower for this kind of plan: I don't want to base my migration plans on a discontinued library.

I really think we should keep Grpc.Core alive for longer, even if I'm the first that would prefer using Grpc.Net.Client everywhere.

**Comment by srini85** [comment]
I am also keen to know what is the minimum version of windows server required here.

**Comment by mnye** [comment]
As per https://docs.microsoft.com/en-gb/aspnet/core/grpc/netstandard?view=aspnetcore-5.0 I think this version of windows is not a general release (yet) but I'm still not sure how to opt-in to it.  I just fully updated my workstation and WinHttpHandler still is not working for me, so for me it unfortunately isn't a solution for .NET Framework at the moment.

![image](https://user-images.githubusercontent.com/6638406/140256065-bc7aecf0-725a-4b0c-8b3b-4e07fd70f1c0.png)

**Comment by Jascen** [comment]
Just noting for others that as of Win10 21H2 (build 19044.1415), bidirectional streaming is still not available.

[The tests](https://github.com/dotnet/runtime/blob/7ac45bdf3c4cba9a48c5b557d6591348df10a603/src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/BidirectionStreamingTest.cs#L25) are tracking a build version that bidirectional streaming may be available in (10.0.22357.0 at the time of writing this).

Adding my experience in here in case it helps anyone else find this:
- My client called ResponseStream.MoveNext() and the Server logged `(Grpc.AspNetCore.Server.ServerCallHandler) Request protocol of '"HTTP/1.1"' is not supported.`
- [This test](https://github.com/dotnet/runtime/blob/7ac45bdf3c4cba9a48c5b557d6591348df10a603/src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/BidirectionStreamingTest.cs#L333) indicates `If WinHTTP doesn't support streaming a request without a length then it will fallback to HTTP/1.1.`
