### ISSUE TITLE
We have a solid understanding of how well the .NET ecosystem serves our users 

### ISSUE THREAD

**Issue by terrajobst** [dotnet/core#5727]
### User Stories

* [ ] [As a .NET OSS class library author, my concerns are heard](https://github.com/dotnet/core/issues/5728)
* [ ] [As a .NET OSS maintainer, I understand how .NET compares to other ecosystems](https://github.com/dotnet/core/issues/5729)
* [ ] [As a .NET platform team member, I understand whether Java-style shading would be a useful feature](https://github.com/dotnet/core/issues/5730)

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
