### ISSUE TITLE
[EPIC] Rate limiting

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/core#6196]
- [ ] Resource limit API design https://github.com/dotnet/aspnetcore/issues/32030
- [ ] Redis based Resource Limiter shipped in aspnetcore
- [ ] Limits in Kestrel https://github.com/dotnet/aspnetcore/issues/32033
  - [ ] Existing rate limits
  - [ ] Concurrency and rate limits for connections
- [ ] Limiter Middleware https://github.com/dotnet/aspnetcore/issues/32032
- [ ] Uses in BCL types https://github.com/dotnet/aspnetcore/issues/32039
  - [ ] Pipelines
  - [ ] Channels
  - [ ] Streams
  - [ ] HttpClient
- [ ] Adoption in YARP https://github.com/dotnet/aspnetcore/issues/32040
- [ ] Adoption for ATS, ACR, R9, etc https://github.com/dotnet/aspnetcore/issues/32041

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
