### ISSUE TITLE
[Windows] Add support for Windows Server 2025

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9374]
This issue is created to track progress for the work to enable Windows Server 2025 support for .NET 6.0 and 8.0

### Product and Test updates
- [ ] [All teams] Do a compatibility check for the product with the new OS
- [x] #9419
- [ ] #9420
- [ ] [Infra] Replace docker tags used in builds across repos and branches
- [ ] [CLI team] Update CI legs to latest updated Dockerfile
- [x] #9421
- [x] [Acquisition] Add support within nightly repos: https://github.com/dotnet/dotnet-docker/pull/5944
- [ ] [Acquisition] Deploy to master (GA) during next patch release cycle (scheduled for January)

## Release team:
- [x]  Notify .NET Core teams regarding new OS release
- [ ]  Update release manifest files 
- [ ] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [ ] Add OS prerequisites to the dependencies document
- [x] #9422

**Comment by richlander** [comment]
FYI: https://learn.microsoft.com/windows-server/get-started/whats-new-windows-server-2025

**Comment by lbussell** [comment]
I filed this issue to get Server 2025 agent pools added: https://github.com/dotnet/dnceng/issues/3781

**Comment by adegeo** [comment]
@rbhanda @ashnaga When will this land for .NET 8? Is it only after 2025 is out of preview?

**Comment by ashnaga** [comment]
> [@rbhanda](https://github.com/rbhanda) [@ashnaga](https://github.com/ashnaga) When will this land for .NET 8? Is it only after 2025 is out of preview?

Once Server 2025 is out of preview.
