### ISSUE TITLE
[macOS] Add support for macOS Sequoia

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#9470]
This issue is created to track progress for the work to enable [macOS sequoia](https://www.apple.com/newsroom/2024/06/macos-sequoia-takes-productivity-and-intelligence-on-mac-to-new-heights/) support for .NET 8.0 and .NET 9.0

### Product and Test updates
- [ ] [All teams] Do a compatibility check for the product with the new OS
- [x] ~#9471~ Runtime does not need RID changes starting with 8.0.
- [ ] #9472
- [x] ~[Infra] Replace docker tags used in builds across repos and branches~ Docker is not applicable to macOS.
- [ ] [CLI team] Update CI legs to latest updated Dockerfile 
- [ ] #9474
- [x] #9473

## Release team:
- [x]  Notify .NET Core teams regarding new OS release
- [ ] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [ ] Add OS prerequisites to the dependencies document
- [x] Update distro install page

**Comment by mikkeljohnsen** [comment]
When will support for macOS Sequoia available ?

My app keeps crashing, and not sure this could be the problem. It is working fine on macOS < 15

**Comment by xtqqczze** [comment]
https://github.com/dotnet/docs/issues/42365

**Comment by adegeo** [comment]
Completed in the MS Learn docs install page via https://github.com/dotnet/docs/pull/43045
