### ISSUE TITLE
Add support for Windows 11, version 24H2

### ISSUE THREAD

**Issue by ashnaga** [dotnet/core#9523]
https://learn.microsoft.com/en-us/windows/whats-new/whats-new-windows-11-version-24h2

This issue is created to track progress for the work to enable Windows 11-version-24h2 support for .NET 6.0, .NET 8.0 and .NET 9.0.

> Supported Architectures: x86, x64, and Arm64. 

### Product and Test updates
- [ ] [All teams] Do a compatibility check for the product with the new OS
- [ ] [CoreCLR/CoreFX] Runtime / RID Support update
- [x] N/A ~~[Infra] Ensure that the correct Docker images used by teams are built in the dotnet-buildtools-prereqs (if applicable)~~
- [x] N/A ~~[Infra] Replace docker tags used in builds across repos and branches~~
- [x] N/A ~~[CLI team] Update CI legs to latest updated Dockerfile~~
- [ ] [All teams] Update test infrastructure to support the new version
- [x] N/A ~~[Acquisition] Add support within nightly repos~~
- [x] N/A ~~[Acquisition] Deploy to master (GA) during next patch release cycle~~

## Release team:
- [x] Notify .NET Core teams regarding new OS release
- [ ]  Update release manifest files 
- [ ] Update the supported OS content on GitHub and marketing sites. 

## Document updates:
- [ ] Add OS prerequisites to the dependencies document
- [x] Update distro install page

**Comment by mthalman** [comment]
I've crossed out all the Docker-related tasks as N/A. There are no Docker images produced for Windows client, only Windows server.
