### ISSUE TITLE
Windows 11, version 22H2 (Home & Pro) reached end of support on October 8, 2024

### ISSUE THREAD

**Issue by ashnaga** [dotnet/core#9549]
Windows 11, version 22H2 (Home & Pro) reached end of support on October 8, 2024 - https://learn.microsoft.com/en-us/lifecycle/announcements/windows-11-22h2-end-of-updates-home-pro
This issue is created to track progress for the remove support for Windows 11, version 22H2 (Home & Pro) from .NET 6.0 and .NET 8.0

### Repos team to update:

- [ ] Remove installers for the outdated distro
- [ ]  Remove build support
- [ ]  Remove test assets

### Infrastructure Team Accountabilities/Deliverables:

- [ ]  Notification to NetCore Engineering Partners
- [ ]  Remove the outdated version from the hardware pool 

### Release Team

- [ ]  Send Notification to every team in .NET for upcoming addition
- [ ]  Supported OS content gets updated on GitHub and marketing sites. 
- [ ]  Update release manifest files. 
- [ ]  Docker files which are used for install testing needs to be updated. 

### Document updates:
- [ ] Add/Remove OS prerequisites to the dependencies document
- [x] Update distro install page
